Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -46,40 +46,16 @@ jobs:
           echo "${{ secrets.AWS_EC2_KEY }}" > key.pem
           chmod 600 key.pem
 
-   
-      # Paso 3: Actualizar e instalar Docker en la instancia EC2 (Instancia 1)
+      # Paso 2: Actualizar e instalar Docker en la instancia EC2 (Instancia 1)
       - name: Update system and install Docker (Instance 1)
         run: |
-          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.AWS_EC2_HOST_QA1 }} << 'EOF'
-          sudo yum update -y
-          if ! command -v docker &> /dev/null
-          then
-            echo "Docker not found, installing..."
-            sudo yum install -y docker
-            sudo systemctl start docker
-            sudo systemctl enable docker
-          else
-            echo "Docker is already installed."
-          fi
-          sudo systemctl start docker
-          sudo systemctl enable docker
-          EOF 
-
-      # Paso 4: Desplegar el contenedor Docker en la instancia EC2 (Instancia 1)
+          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.AWS_EC2_HOST_QA1 }} "sudo yum update -y"
+          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.AWS_EC2_HOST_QA1 }} "if ! command -v docker &> /dev/null; then echo 'Docker not found, installing...'; sudo yum install -y docker; sudo systemctl start docker; sudo systemctl enable docker; else echo 'Docker is already installed.'; fi"
+      
+      # Paso 3: Desplegar el contenedor Docker en la instancia EC2 (Instancia 1)
       - name: Deploy Docker Container (Instance 1)
         run: |
-          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.AWS_EC2_HOST_QA1 }} << 'EOF'
-          sudo docker stop user-auth-microservices || true
-          sudo docker rm user-auth-microservices || true
-          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/user-auth-microservices:latest
-          sudo docker run -d \
-            -p 3000:3000 \
-            --name user-auth-microservices \
-            -e DB_HOST=${{ secrets.DB_HOST }} \
-            -e DB_USER=${{ secrets.DB_USER }} \
-            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
-            -e DB_NAME=${{ secrets.DB_NAME }} \
-            ${{ secrets.DOCKER_USERNAME }}/user-auth-microservices:latest
-          EOF
-      
-    
+          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.AWS_EC2_HOST_QA1 }} "sudo docker stop user-auth-microservices || true"
+          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.AWS_EC2_HOST_QA1 }} "sudo docker rm user-auth-microservices || true"
+          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.AWS_EC2_HOST_QA1 }} "sudo docker pull ${{ secrets.DOCKER_USERNAME }}/user-auth-microservices:latest"
+          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.AWS_EC2_HOST_QA1 }} "sudo docker run -d -p 3000:3000 --name user-auth-microservices -e DB_HOST=${{ secrets.DB_HOST }} -e DB_USER=${{ secrets.DB_USER }} -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} -e DB_NAME=${{ secrets.DB_NAME }} ${{ secrets.DOCKER_USERNAME }}/user-auth-microservices:latest"
