Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -32,37 +32,42 @@ jobs:
 
   deploy-aws:
     needs: build-and-push
-    runs-on: ubuntu-latest 
+    runs-on: ubuntu-latest
 
     steps:
-    - name: Set permissions for private key
-      run: |
-        echo "${{ secrets.AWS_EC2_KEY }}" > key.pem
-        chmod 600 key.pem
+      # Paso 1: Configurar la clave privada para AWS EC2
+      - name: Set permissions for private key
+        run: |
+          echo "${{ secrets.AWS_EC2_KEY }}" > key.pem
+          chmod 600 key.pem
 
-    # Update and configure the first instance
-    - name: Update system and install Docker (Instance 1)
-      run: |
-        ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.AWS_EC2_HOST_QA1 }} << 'EOF'
-        sudo yum update -y
-        if ! command -v docker &> /dev/null
-        then
-          echo "Docker not found, installing..."
-          sudo yum install -y docker
-          sudo systemctl start docker
-          sudo systemctl enable docker
-        else
-          echo "Docker is already installed."
-        fi
-        sudo systemctl start docker
-        sudo systemctl enable docker
-        EOF
-
-    - name: Deploy Docker Container (Instance 1)
-      run: |
-        ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.AWS_EC2_HOST_QA1 }} << 'EOF'
-        sudo docker stop user-auth-microservices || true
-        sudo docker rm user-auth-microservices || true
-        sudo docker pull ${{ secrets.DOCKER_USERNAME }}/user-auth-microservices:latest
-        sudo docker run -d -p 3000:3000 --name user-auth-microservices ${{ secrets.DOCKER_USERNAME }}/user-auth-microservices:latest
-        EOF
+          - name: Update system and install Docker (Instance 1)
+          run: |
+            ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.AWS_EC2_HOST_QA1 }} << 'EOF'
+            sudo yum update -y
+            if ! command -v docker &> /dev/null
+            then
+              echo "Docker not found, installing..."
+              sudo yum install -y docker
+              sudo systemctl start docker
+              sudo systemctl enable docker
+            else
+              echo "Docker is already installed."
+            fi
+            sudo systemctl start docker
+            sudo systemctl enable docker
+            EOF
+  
+        # Paso 3: Desplegar el contenedor Docker en la instancia EC2 (Instancia 1)
+      - name: Deploy Docker Container (Instance 1)
+        run: |
+            ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.AWS_EC2_HOST_QA1 }} << 'EOF'
+            sudo docker stop user-auth-microservices || true
+            sudo docker rm user-auth-microservices || true
+            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/user-auth-microservices:latest
+            sudo docker run -d \
+              -p 3000:3000 \
+              --name user-auth-microservices \
+              --env-file .env \
+              ${{ secrets.DOCKER_USERNAME }}/user-auth-microservices:latest
+            EOF
